name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: mjrk
  GITHUB_REPOSITORY: ayudoo/odoo_business_relationships
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install sphinx build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/buildsite.sh"
        shell: bash
